# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source/main.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 114)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStatusTip("")
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_Button.setObjectName("clear_Button")
        self.horizontalLayout.addWidget(self.clear_Button)
        self.reset_Button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_Button.setObjectName("reset_Button")
        self.horizontalLayout.addWidget(self.reset_Button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.input_Layout = QtWidgets.QGridLayout()
        self.input_Layout.setObjectName("input_Layout")
        self.x_Label = QtWidgets.QLabel(self.centralwidget)
        self.x_Label.setObjectName("x_Label")
        self.input_Layout.addWidget(self.x_Label, 0, 2, 1, 1)
        self.n_Label = QtWidgets.QLabel(self.centralwidget)
        self.n_Label.setObjectName("n_Label")
        self.input_Layout.addWidget(self.n_Label, 1, 2, 1, 1)
        self.n_Input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_Input.sizePolicy().hasHeightForWidth())
        self.n_Input.setSizePolicy(sizePolicy)
        self.n_Input.setMaximumSize(QtCore.QSize(75, 16777215))
        self.n_Input.setObjectName("n_Input")
        self.input_Layout.addWidget(self.n_Input, 1, 3, 1, 1)
        self.x0_Input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x0_Input.sizePolicy().hasHeightForWidth())
        self.x0_Input.setSizePolicy(sizePolicy)
        self.x0_Input.setMaximumSize(QtCore.QSize(75, 16777215))
        self.x0_Input.setObjectName("x0_Input")
        self.input_Layout.addWidget(self.x0_Input, 0, 1, 1, 1)
        self.x_Input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_Input.sizePolicy().hasHeightForWidth())
        self.x_Input.setSizePolicy(sizePolicy)
        self.x_Input.setMaximumSize(QtCore.QSize(75, 5555555))
        self.x_Input.setInputMask("")
        self.x_Input.setObjectName("x_Input")
        self.input_Layout.addWidget(self.x_Input, 0, 3, 1, 1)
        self.y0_Label = QtWidgets.QLabel(self.centralwidget)
        self.y0_Label.setObjectName("y0_Label")
        self.input_Layout.addWidget(self.y0_Label, 1, 0, 1, 1)
        self.y0_Input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y0_Input.sizePolicy().hasHeightForWidth())
        self.y0_Input.setSizePolicy(sizePolicy)
        self.y0_Input.setMaximumSize(QtCore.QSize(75, 16777215))
        self.y0_Input.setObjectName("y0_Input")
        self.input_Layout.addWidget(self.y0_Input, 1, 1, 1, 1)
        self.x0_Label = QtWidgets.QLabel(self.centralwidget)
        self.x0_Label.setObjectName("x0_Label")
        self.input_Layout.addWidget(self.x0_Label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.input_Layout, 0, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.solutions_Button = QtWidgets.QPushButton(self.centralwidget)
        self.solutions_Button.setObjectName("solutions_Button")
        self.verticalLayout_2.addWidget(self.solutions_Button)
        self.error_Button = QtWidgets.QPushButton(self.centralwidget)
        self.error_Button.setObjectName("error_Button")
        self.verticalLayout_2.addWidget(self.error_Button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.clear_Button.clicked.connect(self.n_Input.clear)
        self.clear_Button.clicked.connect(self.x0_Input.clear)
        self.clear_Button.clicked.connect(self.y0_Input.clear)
        self.clear_Button.clicked.connect(self.x_Input.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DE Computational Assignment"))
        self.clear_Button.setToolTip(_translate("MainWindow", "Clear input fields"))
        self.clear_Button.setText(_translate("MainWindow", "Clear"))
        self.reset_Button.setToolTip(_translate("MainWindow", "Reset input to default"))
        self.reset_Button.setText(_translate("MainWindow", "Reset"))
        self.x_Label.setText(_translate("MainWindow", "X"))
        self.n_Label.setText(_translate("MainWindow", "N"))
        self.n_Input.setToolTip(_translate("MainWindow", "A positive integer"))
        self.n_Input.setText(_translate("MainWindow", "100"))
        self.x0_Input.setToolTip(_translate("MainWindow", "A rational number"))
        self.x0_Input.setText(_translate("MainWindow", "1"))
        self.x_Input.setToolTip(_translate("MainWindow", "A rational number greater than x<sub>0</sub>"))
        self.x_Input.setText(_translate("MainWindow", "6"))
        self.y0_Label.setText(_translate("MainWindow", "y<sub>0</sub>"))
        self.y0_Input.setToolTip(_translate("MainWindow", "A rational number"))
        self.y0_Input.setText(_translate("MainWindow", "2"))
        self.x0_Label.setText(_translate("MainWindow", "x<sub>0</sub>"))
        self.label.setText(_translate("MainWindow", "Plot:"))
        self.solutions_Button.setText(_translate("MainWindow", "Solutions"))
        self.error_Button.setText(_translate("MainWindow", "Errors"))
